In this part of the assignment you have to implement multivariate gradient descent to find the minimas (local and global) of the given function:
Note : you can find different minimas by changing your initialisation.  
$f(x) = x^4 + x^2y^2 - y^2 + y^4 + 6$

In [ ]:
import numpy as np

In [ ]:
def call_func(func):
    def wrapper():
        func()
    return wrapper

In [ ]:
def derivative(f, positions):
    positions = np.array(positions)
    print(positions)
    return np.array([4*positions[0]**3 + 2*positions[0]*positions[1]**2, 4*positions[1]**3 -2*positions[1] + 2*positions[1]*positions[0]**2])

In [ ]:
def multivariable_gradient_descent(func, positions, alpha = 0.1):
    epsilon = 1e-5
    weights = np.ones(len(positions))
    count = 0
    while abs(sum(weights)) > epsilon:
        count += 1
        weights = derivative(func, positions)
        positions -= weights/max(100, abs(sum(weights)))
    return positions, count

In [ ]:
positions = [1,2]
func = 5
multivariable_gradient_descent(func, positions)

[1 2]
[0.88 1.68]
[0.80306688 1.49791488]
[0.74631283 1.37411478]
[0.70150186 1.28250624]
[0.66461645 1.21115402]
[0.63337516 1.15361202]
[0.60635349 1.10601847]
[0.58260134 1.06588729]
[0.56145333 1.03153043]
[0.54242551 1.00175345]
[0.52515511 0.97568291]
[0.50936335 0.9526626 ]
[0.49483154 0.9321883 ]
[0.48138507 0.91386505]
[0.46888241 0.89737837]
[0.45720734 0.88247423]
[0.44626328 0.86894484]
[0.43596917 0.85661832]
[0.42625636 0.84535106]
[0.41706621 0.83502204]
[0.40834828 0.82552837]
[0.40005886 0.81678202]
[0.39215988 0.80870711]
[0.38461797 0.80123783]
[0.37740374 0.79431681]
[0.37049116 0.78789378]
[0.36385712 0.78192443]
[0.35748096 0.77636958]
[0.35134419 0.77119442]
[0.34543018 0.76636791]
[0.33972392 0.76186226]
[0.33421184 0.7576525 ]
[0.32888162 0.75371616]
[0.32372203 0.75003291]
[0.31872285 0.74658434]
[0.31387471 0.74335371]
[0.30916904 0.74032578]
[0.30459796 0.73748663]
[0.3001542  0.73482353]
[0.29583107 0.73232478]
[0.29162239 0.72997965]
[0.28752243 0.72777826

(array([9.81895426e-06, 7.07106781e-01]), 1053)

In [ ]:
positions = np.array([-2,-2], dtype='float64')
func = 5
multivariable_gradient_descent(func, positions)

[-2. -2.]
[-1.52 -1.56]
[-1.30554624 -1.36725888]
[-1.16772498 -1.24575757]
[-1.06778932 -1.15936663]
[-0.99038572 -1.09378275]
[-0.9278312  -1.04185901]
[-0.87573883 -0.9995218 ]
[-0.83137599 -0.96423856]
[-0.79293103 -0.9343337 ]
[-0.7591449  -0.90864516]
[-0.72910951 -0.88633659]
[-0.70215005 -0.8667878 ]
[-0.67775243 -0.84952734]
[-0.65551682 -0.83418926]
[-0.63512663 -0.82048444]
[-0.6163273  -0.80818086]
[-0.59891144 -0.79708984]
[-0.58270798 -0.78705608]
[-0.56757442 -0.77795042]
[-0.55339087 -0.7696644 ]
[-0.54005563 -0.76210618]
[-0.52748177 -0.75519735]
[-0.51559448 -0.74887056]
[-0.50432892 -0.74306754]
[-0.49362862 -0.73773757]
[-0.48344413 -0.7328363 ]
[-0.47373187 -0.72832472]
[-0.46445336 -0.72416838]
[-0.45557437 -0.72033671]
[-0.44706441 -0.71680248]
[-0.4388962  -0.71354134]
[-0.43104521 -0.71053144]
[-0.42348938 -0.70775313]
[-0.41620874 -0.70518862]
[-0.40918521 -0.70282184]
[-0.40240237 -0.70063818]
[-0.39584523 -0.69862433]
[-0.38950012 -0.69676815]
[-0.38335454 -

(array([-9.87073315e-06, -7.07106781e-01]), 1073)

In [ ]:
positions = np.array([50,50], dtype='float64')
func = 5
positions
multivariable_gradient_descent(func, positions)

[50. 50.]
[49.49996666 49.50003334]
[48.99993321 49.00006679]
[48.49989964 48.50010036]
[47.99986593 48.00013407]
[47.49983209 47.50016791]
[46.9997981 47.0002019]
[46.49976395 46.50023605]
[45.99972964 46.00027036]
[45.49969515 45.50030485]
[44.99966048 45.00033952]
[44.49962561 44.50037439]
[43.99959054 44.00040946]
[43.49955524 43.50044476]
[42.99951972 43.00048028]
[42.49948396 42.50051604]
[41.99944793 42.00055207]
[41.49941164 41.50058836]
[40.99937507 41.00062493]
[40.49933819 40.50066181]
[39.999301 40.000699]
[39.49926347 39.50073653]
[38.9992256 39.0007744]
[38.49918735 38.50081265]
[37.99914871 38.00085129]
[37.49910966 37.50089034]
[36.99907018 37.00092982]
[36.49903025 36.50096975]
[35.99898983 36.00101017]
[35.49894891 35.50105109]
[34.99890745 35.00109255]
[34.49886543 34.50113457]
[33.99882281 34.00117719]
[33.49877957 33.50122043]
[32.99873566 33.00126434]
[32.49869106 32.50130894]
[31.99864571 32.00135429]
[31.49859959 31.50140041]
[30.99855264 31.00144736]
[30.498504

(array([9.81821170e-06, 7.07106781e-01]), 1169)

In [ ]:
import numpy as np

# Define the function
def f(x, y):
    return x**4 + x**2 * y**2 - y**2 + y**4 + 6

# Compute the function values at the given points
points = [(0, 0), (0, 1), (0, -0.7), (0, 0.8), (0, 0.7)]
values = [f(x, y) for x, y in points]

# Identify the minimum and maximum values
min_value = min(values)
max_value = max(values)
min_point = points[values.index(min_value)]
max_point = points[values.index(max_value)]

min_value, max_value, min_point, max_point, values


(5.7501, 6, (0, -0.7), (0, 0), [6, 6, 5.7501, 5.7696, 5.7501])